<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-H4OHDH0" ignored="2" name="Hub Spot Regression Test Cases" tests="1" failures="1" timestamp="10 May 2021 12:55:02 GMT" time="30.745" errors="0">
  <testcase name="verifyLogin" time="21.655" classname="com.MyTest.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [actiTIME -  Enter Time-Track] but found [actiTIME - Enter Time-Track]">
      <![CDATA[java.lang.AssertionError: expected [actiTIME -  Enter Time-Track] but found [actiTIME - Enter Time-Track]
	at com.MyTest.LoginTest.verifyLogin(LoginTest.java:34)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogin -->
  <testcase name="verifyLoginPageTitleTest" time="0.0" classname="com.MyTest.LoginTest">
    <ignored/>
  </testcase> <!-- verifyLoginPageTitleTest -->
  <testcase name="verifyLoginPageHeaderTest" time="0.0" classname="com.MyTest.LoginTest">
    <ignored/>
  </testcase> <!-- verifyLoginPageHeaderTest -->
</testsuite> <!-- Hub Spot Regression Test Cases -->
